FROM alpine:3.14.0

RUN apk --update --no-cache add g++ git curl bash nodejs yarn python3-dev py3-pip py-pandas && \
  pip3 install --upgrade pip && \
  pip install python-dotenv mysql-connector-python && \
  pip install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint && \
  pip cache purge

WORKDIR /bot
COPY ./ ./
RUN yarn install && \
  yarn build && \
  yarn cache clean

ENTRYPOINT [ "./entrypoint.sh" ]